config/routes.rb
        resource :payments, only: [:new, :create], controller: 'bookings/payments' do
          member do
            post :create_express_checkout_payment
            get :payment_success
          end
        end
        member do
          put :cancel
        end
      end

      resources :company_details, only: [:index, :show, :new, :create, :edit, :update] do
        resources :cost_centers, only: [:index, :show, :new, :create, :edit, :update], controller: 'company_details/cost_centers', shallow: true do
          resources :travelers, only: [:show, :new, :create, :edit, :update], controller: 'company_details/cost_centers/travelers', shallow: true do
            member do
              post :traveler_to_user
            end
            resources :credit_cards, except: [ :destroy ], controller: 'company_details/cost_centers/travelers/credit_cards', shallow: true
          end
        end

        resources :job_titles, only: [:index, :show, :new, :create, :edit, :update], controller: 'company_details/job_titles', shallow: true

      end

      resources :consultants, only: [:index, :show, :new, :create, :edit, :update]

      get '/bookings/:id/payment_result', to: 'payments#result', as: 'payment_result'


      devise_for :users,
               controllers: { sessions:           'public/sessions',
                              passwords:          'public/passwords',
                              registrations:      'public/registrations'
                            }, path: '/'

      get  '/profile', to: 'users#edit', as: 'user_profile'
      patch  '/profile', to: 'users#update', as: 'user'

      patch  '/profile_address/:booking_id', to: 'users#update_address', as: 'user_update_address'

      #get '/friend_hq', to: 'home#friend_hq', as: 'friend_hq'

      #get '/indicate_and_earn/:id', to: 'home#indicate_and_earn', as: '/indicate_and_earn'

      #get '/hours_discount', to:'home#hours_discount', as: 'hours_discount'

      # get '/black_friday', to:'home#black_friday', as: 'black_friday'

      #get '/summer', to:'home#summer', as: 'summer'

      #get '/twelve_hours_discount', to:'home#twelve_hours_discount', as: 'twelve_hours_discount'

      get '/about_us', to: 'home#about_us', as: 'about_us'

      get '/how_it_works', to: 'home#how_it_works', as: 'how_it_works'

      get '/terms_of_use', to: 'home#terms_of_use', as: 'terms_of_use'

      get '/faq', to: 'home#faq', as: 'faq'

      get '/get_booking_packs/:by_hotel_id', to: 'home#get_booking_packs', as: 'get_booking_packs'

      post '/booking_pack_contracting_company', to: 'home#booking_pack_contracting_company', as: 'booking_pack_contracting_company'

      get '/business_trips', to: 'home#business_trips', as: 'get_business_trips'

      post '/business_trips', to: 'home#business_trips', as: 'post_business_trips'

      get '/be_our_partner', to: 'home#be_our_partner', as: 'get_be_our_partner'

      post '/be_our_partner', to: 'home#be_our_partner', as: 'post_be_our_partner'

      get '/privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'

      get '/customer_service', to: 'home#customer_service', as: 'customer_service'
      
      get '/customer_service_corp', to: 'home#customer_service_corp', as: 'customer_service_corp'
      
      # get '/tudo-azul', to: 'home#tudo_azul', as: 'tudo_azul'

      # get '/multiplus', to: 'home#multiplus', as: 'multiplus'

      # get '/uber', to: 'home#uber', as: 'uber'

      # get '/brahma', to: 'home#brahma', as: 'brahma'

      get '/airport', to: 'places#index_airport', as: 'airports'
      get '/city', to: 'places#index_city', as: 'cities'
      get '/place/airports/:id/:place_name', to: 'places#airports', as: 'airport'
      get '/place/cities/:id/:place_name', to: 'places#cities', as: 'city'
      get '/place/regions/:id/:place_name', to: 'places#regions', as: 'region'

      get '/cities', to: 'places#json_cities', format: 'json'
      get '/states', to: 'places#json_states', format: 'json'

      # resources :travel_requests, only: [:index, :show, :new, :create, :edit, :update], path: 'passagens-aereas' do
      #   member do
      #     post :disapprove
      #     post :fills_passenger
      #     post :pay_with_invoiced
      #     put :cancel
      #   end
      # end

    end

  end # of public namespace

  namespace :public_affiliate, path:'affiliate' do
    get '/timezone', to: 'home#timezone', as: 'home'

    resources :hotel_search_logs, only: [] do
      collection do
        post :set_email_for_last_log
      end
    end

    resources :promotional_code_logs, only: [] do
      collection do
        post :check_promotional_code
        post :check_promotional_code_without_creation
      end
    end

    namespace :api, defaults: {format: "json"} do
      namespace :v1 do
=begin
        devise_for :affiliates,
         controllers: { sessions:           'public_affiliate/api/v1/sessions'
                      }, path: '/'
=end
        resources :cities,  only: [:index]
        resources :hotels,  only: [:index, :show] do
          resources :rooms, only: [:index, :show]
        end
        ### booking action index was removed for security purposes
        resources :bookings, only: [:create, :destroy, :show, :new] do
          member do
            put :cancel
          end
          resource :payments, only: [] do
            member do
              # post :create_payment_epyaco
              post :create_payment_paypal
              post :create_payment_maxipago
              post :create_payment_billed
              # post :token
            end
          end
        end
        resources :currencies,  only: [:index]
        get '/hotel_offers', to: 'hotels#offers_per_hotel'
        get '/city_offers', to: 'hotels#offers_per_city'
        get '/offers', to: 'hotels#offers_per_price'
        get '/countries', to: 'hotels#countries'
        get '/hotel_list', to: 'hotels#hotel_list'
        get '/city_hotel/:city', to: 'hotels#hotel_list_by_city'

         get '/hotel_groups/:id', to: 'hotel_chains#hotels_by_hotel_groups'
         get '/hotel_groups', to: 'hotel_chains#hotel_groups'

         get '/lat_lng', to: 'locations#lat_lng'
      end
    end


    localized do
      root to: 'home#index'

      get '/search', to: 'hotel#index', as: 'hotels'

      get '/search/hotel_details/:id/(:name)', to: 'hotel#show', as: 'hotel'

      get '/search/hotel_details/:hotel_id-:hotel_name/room_type_details/:id', to: 'hotel#hotel_room_type_show', as: 'hotel_room_type_show'

      get '/search/map_show/:id', to: 'hotel#hotel_map_show', as: 'hotel_map_show'

      resources :bookings, only: [:index, :show, :new, :create, :edit, :update] do
        resource :payments, only: [:new, :create], controller: 'bookings/payments' do
          member do
            post :create_express_checkout_payment
            get :payment_success
          end
        end
        member do
          put :cancel
        end
      end

      get '/bookings/:id/payment_result', to: 'payments#result', as: 'payment_result'


      devise_for :users,
               controllers: { sessions:           'public_affiliate/sessions',
                              passwords:          'public_affiliate/passwords',
                              registrations:      'public_affiliate/registrations'
                            }, path: '/'

      get  '/profile', to: 'users#edit', as: 'user_profile'
      patch  '/profile', to: 'users#update', as: 'user'

      patch  '/profile_address/:booking_id', to: 'users#update_address', as: 'user_update_address'

      get '/about_us', to: 'home#about_us', as: 'about_us'

      get '/how_it_works', to: 'home#how_it_works', as: 'how_it_works'

      get '/terms_of_use', to: 'home#terms_of_use', as: 'terms_of_use'

      get '/faq', to: 'home#faq', as: 'faq'

      get '/business_trips', to: 'home#business_trips', as: 'get_business_trips'

      post '/business_trips', to: 'home#business_trips', as: 'post_business_trips'

      get '/be_our_partner', to: 'home#be_our_partner', as: 'get_be_our_partner'

      post '/be_our_partner', to: 'home#be_our_partner', as: 'post_be_our_partner'

      get '/privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'

      get '/customer_service', to: 'home#customer_service', as: 'customer_service'

      get '/customer_service_corp', to: 'home#customer_service_corp', as: 'customer_service_corp'

      # get '/tudo-azul', to: 'home#tudo_azul', as: 'tudo_azul'

      # get '/multiplus', to: 'home#multiplus', as: 'multiplus'

      get '/meeting_room', to: 'home#meeting_rooms'

      get '/meeting_room/search', to: 'hotel#meeting_room_hotel_chain'

      # get '/uber', to: 'home#uber', as: 'uber'

      # get '/brahma', to: 'home#brahma', as: 'brahma'
    end
  end # of public affiliate namespace

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      post '/register_device/:device', to: 'devices#create', as: 'register_device'
      resources :hotels, only: [:index, :show] do
        collection {
          #get '/search', to: 'hotel#index'
          #get '/search/hotel_details/:id', to: 'hotel#show'
          get '/room_type_details/:id', to: 'hotels#hotel_room_type_show', as: 'hotel_room_type_show'
          get '/search/map_show/:id', to: 'hotel#hotel_map_show', as: 'hotel_map_show'
        }
      end
    end

    namespace :v2 do
      post '/register_device/:device', to: 'devices#create', as: 'register_device'
      resources :hotels, only: [:index, :show] do
        collection {
          #get '/search', to: 'hotel#index'
          #get '/search/hotel_details/:id', to: 'hotel#show'
          get '/room_type_details/:id', to: 'hotels#hotel_room_type_show', as: 'hotel_room_type_show'
          get '/search/map_show/:id', to: 'hotel#hotel_map_show', as: 'hotel_map_show'
        }

      end

      resources :bookings, only: [:create, :show] do
        member do
          put :cancel
        end

app/views/layouts/public_affiliate/personalized_affiliate/multiplus/_billing_information.html.slim
ruby:
  countries_accepted_by_paypal_iframe = ["BR","US","MX"]
  currencies_accepted_by_paypal_iframe = ["BRL","USD","MXN"]
  can_show_iframe = currencies_accepted_by_paypal_iframe.include?(current_currency.code) && countries_accepted_by_paypal_iframe.include?(@booking.guest.country)
  if @booking.guest.country == "BR" && current_currency.code != "BRL"
    can_show_iframe = false
  end
  
  case I18n.locale.to_s
    when 'pt_br' 
      language_to_paypal = 'pt_BR'
    when 'en'
      language_to_paypal = 'en_US'
    when 'es'
      language_to_paypal = 'es_MX'
    else
      language_to_paypal = 'en_US'
  end

  if @booking.guest.country == "BR"
    tax_id = @booking.guest.cpf.gsub(/\D/, '')
    tax_id_type = "BR_CPF"
  else
    tax_id = ''
    tax_id_type = ''
  end

javascript:
  var ppp = PAYPAL.apps.PPP({ 
    "approvalUrl": "#{raw @redirect_url}",
    "payerFirstName": "#{@booking.guest.first_name}",
    "payerLastName": "#{@booking.guest.last_name}",
    "payerEmail": "#{@booking.guest.email}",
    "payerTaxId": "#{tax_id}",
    "payerPhone": "#{@booking.phone_number.gsub(/\D/, '')}",
    "payerTaxIdType": "#{tax_id_type}",
    "placeholder": "ppplus",
    "language": "#{language_to_paypal}",
    "country": "#{@booking.guest.country}",
    "mode": "live",
    "buttonLocation": "outside",
    "disableContinue": "continueButton",
    "disallowRememberedCards": true,
    "onContinue": function () {
      $("#new_payment").submit();
    },
    "onError": function () {
      $("button.submit-button").attr("disabled", false);
    },
    });

- promotional_100_percent = @booking.promotional_code_log && @booking.promotional_code_log.promotional_code.discount_type == PromotionalCode::ACCEPTED_DISCOUNT_TYPE[:percentage] && @booking.promotional_code_log.promotional_code.discount.eql?(100)
= simple_form_for(@payment, url:  public_affiliate_booking_payments_path(booking_id: params[:booking_id]), method: :post, wrapper: :basic) do |f|
  .col-sm-7
    = render partial: "/public_affiliate/bookings/payments/_new/radio_buttons_form"
    
    .row.info-header ng-init="participantCpf = false; multiplusParticipant = false"
      .info-price.col-xs-12.col-md-2.text-right.hidden-md.hidden-lg
        - if promotional_100_percent
          .row
            = t(:promotional_100_percent_describe)


    .hidden-xs.hidden-sm
      .booking-step-title
        - if promotional_100_percent
          = t(:promotional_100_percent_describe)

    

    - if !promotional_100_percent
      - if @booking.traveler_id.present? && !current_public_affiliate_user.accept_confirmed_and_invoiced
        - options_for_select = []
        - credit_cards = @booking.traveler.credit_cards
        - credit_cards.each do | credit_card |
          - options_for_select << ["#{t("payments.#{credit_card.flag_name}")} - #{t(:last_digits)}: #{credit_card.last_four_digits}", credit_card.id]
        .form-group.select-credit-cards ng-controller='TravelerCreditCardCtrl' ng-init="creditCardsTraveler = #{credit_cards.to_json}"
          = select_tag 'credit_card[id]', options_for_select(options_for_select), class: 'select form-control size-100-percent', prompt: t(:select_the_credit_card), 'ng-model' => 'selectedCreditCardId', 'ng-change' => 'changeCreditCard()'
          .show-credit-card.collapse
            .row
              .col-sm-8
                => CreditCard.human_attribute_name("card_number") + ":"
                span.card-number-value
              .col-sm-4
                => CreditCard.human_attribute_name("cvv") + ":"
                span.cvv-value
            .row
              .col-sm-6
                => CreditCard.human_attribute_name("expiration_month") + ":"
                span.expiration-month-value
              .col-sm-6
                => CreditCard.human_attribute_name("expiration_year") + ":"
                span.expiration-year-value


    .row ng-init="paypalCreditCard = #{can_show_iframe}"
      - if can_show_iframe
        .col-sm-6
          label.radio-button for='paypal_credit_card_true' ng-click='paypalCreditCard = true'
            = radio_button_tag 'paypal_credit_card', true, (params[:paypal_credit_card] == 'true') || (params[:paypal_credit_card].nil?), class: "cpy-credit-card-true-radio-button", "ng-checked" => "paypalCreditCard"
            =< t(:credit_card)

      .col-sm-6
        label.radio-button for='paypal_credit_card_false' ng-click='paypalCreditCard = false'
          = radio_button_tag 'paypal_credit_card', false, (params[:paypal_credit_card] == 'false'), class: "cpy-credit-card-false-radio-button", "ng-checked" => "!paypalCreditCard"
          =< image_tag("https://www.paypalobjects.com/webstatic/en_US/i/buttons/PP_logo_h_100x26.png")


      - if !current_public_affiliate_user.accept_confirmed_and_invoiced && can_show_iframe
        #ppplus
        
  .col-sm-5
    = f.input :paypal_payment_id, :as => :hidden
    .form-actions
      .col-sm-12
        .clearfix
        .checkbox ng-init="checkedTermsofuse = true"
          label
            = check_box_tag "read_and_accept", nil, false, "ng-model" => "checkedTermsofuse"
            span.lbl
              =< t(:i_have_read_and_accepted)

        - if can_show_iframe
          div ng-show='paypalCreditCard'
            .js-tooltip-toggler.tooltip-toggler.pull-right data-toggle="tooltip" data-placement="bottom" data-html='true' data-original-title="#{t(:check_terms_of_use_title)}"

              button type="submit" class="submit-disabled cpy-disabled-submit-button #{button_class} submit-button pill big pull-right btn" disabled="disabled" ng-hide="checkedTermsofuse"
                = t(:finish_reservation)

            button type="submit" id="continueButton" onclick="ppp.doContinue(); return false;" class="cpy-submit-button ng-hide #{button_class} submit-button pill big pull-right btn" ng-disabled="!checkedTermsofuse" ng-show="checkedTermsofuse"
              = t(:finish_reservation)


      - if !current_public_affiliate_user.accept_confirmed_and_invoiced
        .clearfix
        #paypal-button ng-show='!paypalCreditCard'


= javascript_include_tag("https://www.paypalobjects.com/api/checkout.js")

javascript:
  paypal.Button.render({
    env: 'production', // Specify 'sandbox' for the test environment
    style: {
      size: 'responsive',
      color: 'blue',
      shape: 'pill',
      label: 'checkout'
    },
    locale: "#{language_to_paypal}",
    payment: function(resolve, reject) {
       
      var CREATE_PAYMENT_URL = "#{create_express_checkout_payment_public_affiliate_booking_payments_path(@booking.id, :authenticity_token => form_authenticity_token)}";
          
      paypal.request.post(CREATE_PAYMENT_URL)
        .then(function(data) { resolve(data.id); })
        .catch(function(err) { reject(err); });
    },
    commit: true, // Optional: show a 'Pay Now' button in the checkout flow
    onAuthorize: function(data) {
    
      // Note: you can display a confirmation page before executing
      
      var EXECUTE_PAYMENT_URL = "#{public_affiliate_booking_payments_path(@booking.id)}?" + $('#new_payment').serialize();

      paypal.request.post(EXECUTE_PAYMENT_URL,
            { paymentID: data.paymentID, payerID: data.payerID })
            
        .then(function(data) { 
          if (data.table.success == true){
            window.location.replace("#{payment_success_public_affiliate_booking_payments_path(@booking.id)}"); 
          }else{
            window.location.replace("#{new_public_affiliate_booking_payments_path(@booking.id)}");
          }
        })

        .catch(function(err) { window.location.replace("#{public_affiliate_booking_payments_path(@booking.id)}"); });
    }

  }, '#paypal-button');

app/views/layouts/public_affiliate/personalized_affiliate/multiplus/_hotel_row.html.slim
- distance = search_row[:distance]
- hotel = search_row[:hotel]
- offer = search_row[:min_offer]
- if similar_hotel
  - row_extra_class = 'js-similar-hotel-row'
.box.js-hotel-row.js-individual-hotel.individual-hotel ng-show="hotelPriceAndCategoryAndDistanceMatchFilter(#{total_price_for_number_of_people(params[:by_number_of_people], offer)},#{hotel.category[0]}, #{hotel.distance_to(@searched_address_coordinates).round(2)})" class="#{row_extra_class}"
  .row.desktop-individual-hotel-row.hidden-xs.hidden-sm
    .hotel-photo-col.col-md-4
      .row
        .col-md-12
          - unless Rails.env.test?
            - hotel_main_photo_url = hotel.main_photo_url
            - if hotel_main_photo_url
              = link_to(public_affiliate_hotel_path(id: hotel.id, name: hotel.name.parameterize, length_of_pack: params[:by_pack_length], checkin_date: params[:by_checkin_date], checkin_hour: params[:by_checkin_hour], number_of_people: params[:by_number_of_people]), class: 'cpy-hotel-details-link') do
                = image_tag hotel_main_photo_url, class: 'hotel-photo', alt: ''
    .hotel-info-col.col-md-8
      .row
        .col-md-12
          .row
            .col-md-7
              .hotel-name
                = link_to(hotel.name, public_affiliate_hotel_path(id: hotel.id, name: hotel.name.parameterize, length_of_pack: params[:by_pack_length], checkin_date: params[:by_checkin_date], checkin_hour: params[:by_checkin_hour], number_of_people: params[:by_number_of_people]))
              .hotel-rating
                = render_stars_from_hotel(hotel)
            .col-md-5
              .hotel-from-price.pull-right.text-right
                = t(:from).downcase
                br
                span = current_currency.money_sign
                span.bigger = number_to_currency(calculate_currency(total_price_for_number_of_people(params[:by_number_of_people], offer), Hotel::CURRENCY_SYMBOL_REVERSED[hotel.currency_symbol]).round, unit: "", precision: 0)
          .row
            .col-md-12
              .hotel-address
                span.map-marker
                  i.glyphicon.glyphicon-map-marker
                span.address
                  = "#{hotel.address}: "
                br
                span.distance
                  = "#{t :distance}: "
                  span.number-distance
                    = "#{distance.to_s.gsub('.',',')} KM"
                span.see-map
                  = link_to public_affiliate_hotel_map_show_path(id: hotel.id, hotel: {latitude: hotel.latitude, longitude: hotel.longitude, name: hotel.name}), "data-toggle" => "modal", "data-target" => ".js-room-type-modal", remote: true do
                    i.glyphicon.glyphicon-globe>
                    = t(:see_map)
          /.row
            .col-md-12
              .hotel-description
                = hotel.send("description_#{I18n.locale}").truncate(200)
          /.row
            .col-md-12
              .hotel-payment-methods
                - payment_methods =  "#{t :payment_methods_accepted_by_the_hotel}: #{hotel.send("payment_method_#{I18n.locale}").downcase.capitalize}"
                - payment_methods += '.' unless payment_methods[-1] == '.'

                => payment_methods
                - if hotel.accept_online_payment?
                  b
                    = t(:this_hotel_accepts_online_payment) + '.'
  - if can_current_public_affiliate_user_afford?(price_without_tax: offer.price, pack_in_hours: params[:by_pack_length])
    .row.hidden-xs.hidden-sm style="margin-top: 4px"
      .col-md-4
        .points-multiplus
          p.product-price-from = t(:accrue)
          p.product-price
            span.strong = multiplus_point(total_price_for_number_of_people(params[:by_number_of_people], offer))
            em = t(:multiplus_points)
      .col-md-6
      .col-md-2
        .pull-right.hotel-details
          = link_to(public_affiliate_hotel_path(id: hotel.id, name: hotel.name.parameterize, length_of_pack: params[:by_pack_length], checkin_date: params[:by_checkin_date], checkin_hour: params[:by_checkin_hour], number_of_people: params[:by_number_of_people]), class: 'btn btn-success cpy-hotel-details-link') do
            = t(:reserve)
  - else
    .row.hidden-xs.hidden-sm
      .col-md-10
      .col-md-2
        .pull-right.hotel-details
          .js-tooltip-toggler.tooltip-toggler data-toggle="tooltip" data-placement="bottom" data-html='true' data-original-title="#{t(:booking_not_allowed_button_title)}"
            = button_tag t(:booking_not_allowed), class: 'btn btn-danger'


  .row.mobile-individual-hotel-row.hidden-md.hidden-lg onclick="location.href='#{public_affiliate_hotel_path(id: hotel.id, name: hotel.name.parameterize, length_of_pack: params[:by_pack_length], checkin_date: params[:by_checkin_date], checkin_hour: params[:by_checkin_hour], number_of_people: params[:by_number_of_people])}';"
    .hotel-photo-col.col-xs-4
      .row
        .col-xs-12
          - unless Rails.env.test?
            - hotel_main_photo_url = hotel.main_photo_url
            - if hotel_main_photo_url
              = image_tag hotel_main_photo_url, class: 'hotel-photo', alt: ''
    .hotel-info-col-mobile.col-xs-8
      .row
        .col-xs-12.hotel-name
          = truncate(hotel.name, length: 30)
      .row.hotel-details
        .col-xs-6.hotel-address
          span.map-marker
            i.glyphicon.glyphicon-map-marker
          span.address
            = "#{truncate(hotel.address, length: 50)}"
          br
          span.distance
            = "#{t :about} #{hotel.distance_to(@searched_address_coordinates).round(1).to_s.gsub('.',',')} KM"
        .col-xs-5.hotel-rating-price
          .row.hotel-rating.text-right
            = render_stars_from_hotel_mobile(hotel)
          .row.hotel-from-price.text-right
            = t(:from).downcase
            br
            span = current_currency.money_sign
            span.bigger = number_to_currency(calculate_currency(total_price_for_number_of_people(params[:by_number_of_people], offer), Hotel::CURRENCY_SYMBOL_REVERSED[hotel.currency_symbol]).round, unit: "", precision: 0)
        .col-xs-1.continue-icon
          i.fa.fa-angle-right

  - if @any_available_voucher && mobile_device?
    p style="display: inline; font-size: 10px"
      | Confirme sua reserva e
      strong  ganhe R$10
      |  para usar com:
    = image_tag 'easy-taxi-logo.png', style: 'display: inline; width: 60px'

app/views/layouts/public_affiliate/personalized_affiliate/multiplus/_with_exact_match_offers.html.slim
.row
  .col-sm-12.border-box.with-padding-bottom
    .row
      .col-sm-12
        p.pack-size
          => t(:pack_of)
          span.big => params[:length_of_pack]
          = t(:hours)
        h4.text-center
          = "#{l(params[:checkin_date].to_date)} #{t(:at)} #{params[:checkin_hour]}:00"
        p.beware.text-center
          | #{ t :beware}:
          - if @hotel.accepts_booking_cancellation?
            - date_parsed = params[:checkin_date].to_date + params[:checkin_hour].to_i.hours - @hotel.minimum_hours_of_notice.hours
            - day_of_notice = l(date_parsed)
            = t(:hotel_minimum_hours_of_notice, day_of_notice: day_of_notice)

          table.table.table-striped.table-hover
            thead
              th.size-5-percent
              th.size-42-percent = t :room_type
              th.size-25-percent = t :price
              th.size-18-percent = "#{t(:accrue)} #{t(:multiplus_points)}"
              th.size-10-percent
            tbody
              - @search_exact_match.each do | search_row |
                tr
                  td style="padding: 8px 4px 8px 12px"
                    - offer = search_row[:min_offer]
                    - room_type = search_row[:room_type]
                    = link_to "", public_affiliate_hotel_room_type_show_path(hotel_id: @hotel.id, hotel_name: @hotel.name.parameterize, id: room_type.id, length_of_pack: params[:length_of_pack], checkin_date: params[:checkin_date], checkin_hour: params[:checkin_hour], number_of_people: params[:number_of_people], offer_price: total_price_for_number_of_people(params[:number_of_people], offer)), class: "glyphicon glyphicon-question-sign big", "data-toggle" => "modal", "data-target" => ".js-room-type-modal", remote: true
                  td.js-room-type-description
                    = room_type.send("full_name_#{I18n.locale}")
                  td.bigger.js-room-type-description
                     = number_to_currency(calculate_currency(total_price_for_number_of_people(params[:number_of_people], offer), Hotel::CURRENCY_SYMBOL_REVERSED[@hotel.currency_symbol]).round, unit: current_currency.money_sign, precision: 0)
                  td.bigger.js-room-type-description
                    = multiplus_point(total_price_for_number_of_people(params[:number_of_people], offer))
                  td.js-room-type-description
                    - if can_current_public_affiliate_user_afford?(price_without_tax: offer.price.to_f, pack_in_hours: params[:length_of_pack])
                      = link_to t(:reserve), new_public_affiliate_booking_path(price: offer.price, checkin_timestamp: (params[:checkin_date].to_datetime + params[:checkin_hour].to_i.hours).strftime("%Y-%m-%d %H:%M:%S +0000"), pack_in_hours: params[:length_of_pack], room_type_id: offer.room_type_id, number_of_people: params[:number_of_people]), class: "pill btn-success small cpy-reserve-offer-button hidden-sm hidden-xs"
                      = link_to "<i class='fa fa-angle-right'></i>".html_safe, new_public_affiliate_booking_path(price: offer.price, checkin_timestamp: (params[:checkin_date].to_datetime + params[:checkin_hour].to_i.hours).strftime("%Y-%m-%d %H:%M:%S +0000"), pack_in_hours: params[:length_of_pack], room_type_id: offer.room_type_id, number_of_people: params[:number_of_people]), class: "js-new-booking arrow-right btn-success cpy-reserve-offer-mobile-button hidden-md hidden-lg"

          p.hint
            => t :click_on_the_icon
            span.glyphicon.glyphicon-question-sign
            =<   t :to_see_more_details_about_the_room_type
        - if @similar_offers_found
          .row
            .col-sm-12
              a.btn.btn-success.js-scroll-button.scroll-button href='#similar-offers'
                => t(:see_similar_offers)
                i.glyphicon.glyphicon-arrow-down

    .row.hidden-md.hidden-lg
      .col-sm-12
        #map-canvas-mobile[style="width:100%; height:400px"]