config/routes.rb
        post :authenticate_as, path: 'acessar-como'
      end
    end

    resources :credit_cards, except: [ :edit, :update, :destroy ], path: 'cartoes-de-credito'
    resources :invoices, except: [ :edit, :update, :destroy ], path: 'dados-para-nf'


  end # of company namespace

  namespace :affiliate, path: 'afiliados', path_names:  { new: 'novo', create: 'novo', edit: 'editar', update: 'editar', remove: 'remover'} do
    root to: 'info#index'

    devise_for :affiliates,
                  controllers: {
                              sessions:           'affiliate/sessions',
                              registrations:      'affiliate/registrations',
                              passwords:          'affiliate/passwords'
                            },
                  path: '/', path_names:{
                                        sign_in: 'entrar',
                                        sign_up: 'registrar',
                                        sign_out: 'sair'
                                       }

    get 'atualizar-informacoes' => 'info#edit', as: :update_info

    patch 'atualizar-informacoes' => 'info#update'

    resources :doc, only: [ :index ], path: 'doc' do
      collection do
        get 'iframe'
        get 'webservice'
        get '/webservice/:version', to: "doc#webservice_version", as: :get_webservice
      end
    end

    resources :bookings, only: [ :index, :show ], path: 'reservas' do
      member do
        put :cancel
      end
    end

    #resources :credit_cards, except: [ :edit, :update, :destroy ], path: 'cartoes-de-credito'
    #resources :invoices, except: [ :edit, :update, :destroy ], path: 'dados-para-nf'


  end # of affiliate namespace

  localized do

    namespace :hotel, path: 'fornecedores', path_names: { new: 'novo', create: 'novo', edit: 'editar', update: 'editar', remove: 'remover'} do
      root to: 'info#index'

      get 'mudar-senha' => 'info#edit', as: :change_password

      patch 'mudar-senha' => 'info#update_password'

      get 'relatorios' => 'reports#index', as: :reports

      scope '/quartos' do
        resources :room_types, path: 'tipos_de_quartos', :except => [:destroy]
        resources :rooms, path: 'quartos', :except => [:update, :destroy, :show, :edit, :new]
        resources :pricing_policies, path: 'tabelas_de_precos'
        resources :room_offers_creator_logs, path: 'relatorios_de_ofertas', controller: 'offers_creator_logs', type: 'RoomOffersCreatorLog', only: [:index]
        resources :offers, path: 'ofertas', only: [:create, :new, :index] do
          collection do
            get :count_per_room
            get :room_types_with_active_rooms
            get :pricing_policies_with_room_types_id
            get :remove
            post :remove
            get :show_all, path: 'listar'
            get :remove_intermediate_step, path: 'remover_confirmacao'
            post :remove_intermediate_step, path: 'remover_confirmacao'
            get :remove_all_offers
            post :remove_all_offers
            get :remove_all_intermediate_step, path: 'remover_todas_confirmacao'
            post :remove_all_intermediate_step, path: 'remover_todas_confirmacao'
          end

        end
      end

      scope '/salas-de-reuniao' do
        resources :meeting_rooms, path: 'salas', :except => [:destroy], controller: 'business_rooms', type: 'MeetingRoom'
        resources :meeting_room_pricing_policies, path: 'tabelas_de_precos', controller: 'business_room_pricing_policies', type: 'MeetingRoomPricingPolicy'
        resources :meeting_room_offers_creator_logs, path: 'relatorios_de_ofertas', controller: 'offers_creator_logs', type: 'MeetingRoomOffersCreatorLog', only: [:index]
        resources :meeting_room_offers, path: 'ofertas', only: [:create, :new, :index] do

          collection do
            get :count_per_room
            get :pricing_policies_with_meeting_room_id
            get :remove
            post :remove
            get :show_all, path: 'listar'
            get :remove_intermediate_step, path: 'remover_confirmacao'
            post :remove_intermediate_step, path: 'remover_confirmacao'
          end

        end
      end

=begin
    scope '/saloes-de-evento' do
      resources :event_rooms, path: 'saloes', :except => [:destroy], controller: 'business_rooms', type: 'EventRoom'
      resources :event_room_pricing_policies, path: 'tabelas_de_precos', controller: 'business_room_pricing_policies', type: 'EventRoomPricingPolicy'
      resources :event_room_offers_creator_logs, path: 'relatorios_de_ofertas', controller: 'offers_creator_logs', type: 'EventRoomOffersCreatorLog', only: [:index]
      resources :event_room_offers, path: 'ofertas', only: [:create, :new, :index] do

        collection do
          get :count_per_room
          get :pricing_policies_with_event_room_id
          get :remove
          post :remove
          get :show_all, path: 'listar'
          get :remove_intermediate_step, path: 'remover_confirmacao'
          post :remove_intermediate_step, path: 'remover_confirmacao'
        end

      end
    end
=end

      devise_for :hotels,
                 controllers: { sessions:           'hotel/sessions',
                                passwords:          'hotel/passwords'
                              },
                 path: '/', path_names:{
                                        sign_in: 'entrar',
                                        sign_out: 'sair'
                                       }


      resources :bookings, path: 'reservas', only: [:index, :show] do
        collection do
          get :rooms, path: 'quartos'
          get :meeting_rooms, path: 'salas-de-reuniao'
          #get :event_rooms, path: 'saloes-de-evento'
        end
        member do
          put :set_as_no_show
          put :accuse_delayed_checkout
          put :hotel_accept_request
          put :hotel_deny_request
        end
      end
    end # of hotel namespace
  end

  namespace :public, path:'/' do
    resources :hotel_search_logs, only: [] do
      collection do
        post :set_email_for_last_log
      end
    end

    resources :promotional_code_logs, only: [] do
      collection do
        post :check_promotional_code
        post :check_promotional_code_without_creation
      end
    end

    resources :referred_friend_logs, only: [] do
      collection do
        post :send_code
      end
    end 

    resources :newsletters, only: [:new, :create]
    get '/timezone', to: 'home#timezone', as: 'home'

    localized do
      root to: 'home#index'

      get '/search', to: 'hotel#index', as: 'hotels'

      get '/search/hotel_details/:id/(:name)', to: 'hotel#show', as: 'hotel'

      get '/search/hotel_details/:hotel_id-:hotel_name/room_type_details/:id', to: 'hotel#hotel_room_type_show', as: 'hotel_room_type_show'

      get '/search/map_show/:id', to: 'hotel#hotel_map_show', as: 'hotel_map_show'

      resources :bookings, only: [:index, :show, :new, :create, :edit, :update] do
        resource :payments, only: [:new, :create], controller: 'bookings/payments' do
          member do
            post :create_express_checkout_payment
            get :payment_success
          end
        end
        member do
          put :cancel
        end
      end

      resources :company_details, only: [:index, :show, :new, :create, :edit, :update] do
        resources :cost_centers, only: [:index, :show, :new, :create, :edit, :update], controller: 'company_details/cost_centers', shallow: true do
          resources :travelers, only: [:show, :new, :create, :edit, :update], controller: 'company_details/cost_centers/travelers', shallow: true do
            member do
              post :traveler_to_user
            end
            resources :credit_cards, except: [ :destroy ], controller: 'company_details/cost_centers/travelers/credit_cards', shallow: true
          end
        end

        resources :job_titles, only: [:index, :show, :new, :create, :edit, :update], controller: 'company_details/job_titles', shallow: true

      end

      resources :consultants, only: [:index, :show, :new, :create, :edit, :update]

      get '/bookings/:id/payment_result', to: 'payments#result', as: 'payment_result'


      devise_for :users,
               controllers: { sessions:           'public/sessions',
                              passwords:          'public/passwords',
                              registrations:      'public/registrations'
                            }, path: '/'

      get  '/profile', to: 'users#edit', as: 'user_profile'
      patch  '/profile', to: 'users#update', as: 'user'

      patch  '/profile_address/:booking_id', to: 'users#update_address', as: 'user_update_address'

      #get '/friend_hq', to: 'home#friend_hq', as: 'friend_hq'

      #get '/indicate_and_earn/:id', to: 'home#indicate_and_earn', as: '/indicate_and_earn'

      #get '/hours_discount', to:'home#hours_discount', as: 'hours_discount'

      # get '/black_friday', to:'home#black_friday', as: 'black_friday'

      #get '/summer', to:'home#summer', as: 'summer'

      #get '/twelve_hours_discount', to:'home#twelve_hours_discount', as: 'twelve_hours_discount'

      get '/about_us', to: 'home#about_us', as: 'about_us'

      get '/how_it_works', to: 'home#how_it_works', as: 'how_it_works'

      get '/terms_of_use', to: 'home#terms_of_use', as: 'terms_of_use'

      get '/faq', to: 'home#faq', as: 'faq'

      get '/get_booking_packs/:by_hotel_id', to: 'home#get_booking_packs', as: 'get_booking_packs'

      post '/booking_pack_contracting_company', to: 'home#booking_pack_contracting_company', as: 'booking_pack_contracting_company'

      get '/business_trips', to: 'home#business_trips', as: 'get_business_trips'

      post '/business_trips', to: 'home#business_trips', as: 'post_business_trips'

      get '/be_our_partner', to: 'home#be_our_partner', as: 'get_be_our_partner'

app/models/meeting_room.rb
class MeetingRoom < BusinessRoom
  
  # relations
  has_many   :meeting_room_offers


  def rooms_with_active_offer_count_per_day(month_number, year)
    initial_timestamp = Time.new(year, month_number).utc.beginning_of_month.strftime("%Y-%m-%d %H:%M:%S")
    last_timestamp = Time.new(year, month_number).utc.end_of_month.strftime("%Y-%m-%d %H:%M:%S")
    query = %Q{
      SELECT COUNT(meeting_room_id) as room_count, day_checkin_timestamp
      FROM (
        SELECT meeting_room_id, extract(day from checkin_timestamp) AS day_checkin_timestamp
        FROM meeting_room_offers
        WHERE
          (meeting_room_offers.checkin_timestamp BETWEEN '#{initial_timestamp}' AND '#{last_timestamp}') AND
          meeting_room_offers.hotel_id = #{hotel_id} AND
          meeting_room_offers.status = #{MeetingRoomOffer::ACCEPTED_STATUS[:available]} AND
          meeting_room_offers.meeting_room_id = #{id}
          GROUP BY extract(day from checkin_timestamp), meeting_room_id
      ) t
      GROUP BY day_checkin_timestamp
    }

    MeetingRoomOffer.connection.execute(query).to_a.inject(Hash.new(0)) do |memo, row_hash|
      memo[row_hash["day_checkin_timestamp"].to_i] = row_hash["room_count"]
      memo
    end
  end
  

end

app/controllers/admin/hotels/meeting_rooms_controller.rb
class Admin::Hotels::MeetingRoomsController < Admin::BaseController
  actions :show, :edit, :update

  belongs_to :hotel

  def update
    update! do |success, failure|
      success.html do
        redirect_to admin_hotel_meeting_room_path(id: @meeting_room, hotel_id: @meeting_room.hotel_id)
      end
    end
  end

  private

  def build_resource_params
    [params.fetch(:meeting_room, {}).permit!]
  end

end

app/views/layouts/public_affiliate/personalized_affiliate/estelar/meeting_room/_mobile_search_form.html.slim
.search-hotels-wrapper
  .col-md-12
    .search-box.js-headline-search

      = render partial: "layouts/public_affiliate/personalized_affiliate/#{layout_name}/meeting_room/mobile_search_form_content"

app/views/layouts/public_affiliate/personalized_affiliate/estelar/meeting_room/_mobile_search_form_content.html.slim
ruby:
  # we must keep in here because there are some controllers in the public area that doen'st inherit from public::base
  ng_init_for_search_form = if last_search_log
    # 0 - day
    # 1 - month
    # 2 - year
    date_parts = last_search_log.checkin_date.split("/")
    english_date_format = "#{date_parts[1]}/#{date_parts[0]}/#{date_parts[2]}"
    %Q{
      checkinDate = '#{I18n.locale == :en ? english_date_format : last_search_log.checkin_date}';
      parsedSelectedCheckinDate = '#{last_search_log.checkin_date}';
      checkinHour = #{last_search_log.checkin_hour};
      numberOfPeople = #{last_search_log.number_of_people};
      selectedPackSize = '#{last_search_log.length_of_pack}';
      selectedTabRoom = 1;
    }.squish
  else
    ""
  end
  tab = 1

= form_tag public_affiliate_hotels_path, method: :get, class: 'form-horizontal', "ng-controller" => "PublicMobileSearchCtrl", "ng-init" => "#{ng_init_for_search_form}" do

  .hidden
    input.cpy-mobile-pack-length type="text" name="by_pack_length" ng-model="selectedPackSize"
    input.cpy-mobile-room-category type="text" name="room_category" ng-model="selectedTabRoom"
    input.cpy-mobile-number-of-people type="text" name="by_number_of_people" ng-model="numberOfPeople"
    
  - if mobile_device?
    .col-md-12.search-form-header.hidden-sm.hidden-md.hidden-lg
      h1.book-hotels
        = t(:book_by_hours)
  .tabbable
    .tab-content.tab-content-custom-mobile
      .tab-pane.fade.in.active#rooms
        .row
          .col-sm-12
            .display-table.people-checkin-inputs
              .display-table-cell.size-78-percent
                .row
                  .col-xs-12
                    .secondary-title = t 'search_box.checkin'
                .row.checkin-mobile
                  .col-xs-6
                    = "#{t(:date_word)}:"
                    br
                    .input-group.date-picker-inputs

                      input.js-date-picker.cpy-checkin-date-calendar-input.js-search-date-picker.form-control.js-mask-date ng-model="checkinDate" ng-change='setSearchDateValidity()'

                      input.hidden.cpy-checkin-date ng-model="parsedSelectedCheckinDate" name='by_checkin_date'

                  .col-xs-6
                    = "#{t(:hour)}:"
                    br
                    - array_hours = []
                    - 24.times do | i |
                      - array_hours << i
                    = select_tag 'by_checkin_hour', options_for_select(array_hours.collect { | hour | ["#{hour}:00", hour]}), class: 'js-checkin-time size-100-percent', 'ng-model' => 'checkinHour'

              .display-table-cell.number-of-people-input-size
                  .up.hidden-xs.hidden-sm = "#{t(:number_of_people)}"
                  .up.hidden-md.hidden-lg = "#{t('search_box.people')}"
                  = select_tag '', options_for_select(1..99), "ng-model" => "numberOfPeople"
              

        .row.pack-size-row
          .col-xs-12
            .display-table.pack-size-table
              .display-table-cell
                .up = "#{t(:pack_size)}"
                .btn-group.pack-size
                  span.clock
                    = image_tag 'clock-light-gray.png'
                  - MeetingRoomOffer::ACCEPTED_LENGTH_OF_PACKS.each do |pack_size|
                    a.btn.rooms class="pack-#{pack_size} cpy-pack-#{pack_size}" ng-class="{selected: selectedPackSize == #{pack_size}}" ng-click="selectedPackSize = #{pack_size}" #{pack_size}h



        .row.pack-size-hint
          .col-xs-12
            p.hint = t :period_in_which_you_are_staying_at_hotel

        .row
          .col-xs-12.text-center
            .js-tooltip-toggler.tooltip-toggler data-toggle="tooltip" data-placement="bottom" data-html='true' data-original-title="#{t(:the_search_button_was_disabled_for_the_following_reasons)}: {{resonsForDisabledSubmit()}}"
              button.submit-disabled.cpy-disabled-search-button.btn.green.search-button disabled='disabled' ng-hide='isFormValid()'
                = t(:perform_search)

            button.cpy-search-button.ng-hide.btn.green.search-button ng-disabled='!isFormValid()' ng-show='isFormValid()'
              = t(:perform_search)
              
      
       
javascript:
  yojs.set('tabNumber' , "#{tab}")        

app/views/layouts/public_affiliate/personalized_affiliate/estelar/meeting_room/_search_form.html.slim
ruby:
  # we must keep in here because there are some controllers in the public area that doen'st inherit from public::base
  ng_init_for_search_form = if last_search_log
    # 0 - day
    # 1 - month
    # 2 - year
    date_parts = last_search_log.checkin_date.split("/")
    english_date_format = "#{date_parts[1]}/#{date_parts[0]}/#{date_parts[2]}"
    length_of_pack = last_search_log.room_category == 1 ? 12 : last_search_log.length_of_pack
    checkin_hour = (last_search_log.room_category == 1 && last_search_log.checkin_hour < 18) ? 18 : last_search_log.checkin_hour
    checkout_hour = checkin_hour + length_of_pack
    if checkout_hour >= 24
      checkout_hour -= 24
    end
      
    %Q{
      latitude = '#{last_search_log.latitude}';
      longitude = '#{last_search_log.longitude}';
      checkinDate = '#{I18n.locale == :en ? english_date_format : last_search_log.checkin_date}';
      parsedSelectedCheckinDate = '#{last_search_log.checkin_date}';
      checkinHour = #{checkin_hour};
      numberOfPeople = #{last_search_log.number_of_people};
      selectedPackSize = '#{last_search_log.length_of_pack}';
      cityName = '#{last_search_log.city_name}';
      stateName = '#{last_search_log.state_name}';
      address = '#{last_search_log.address}';
      selectedTabRoom = '#{last_search_log.room_category || 1}';
      checkoutHour = #{checkout_hour};
      setLatitudeAndLongitudeValidity();
    }.squish
  else
    ""
  end
.gradient_overlay
.search-hotels-wrapper
  .row.describe-home.no-margin
    .col-md-12.hidden-xs
      span 
        | #{t('views.affiliates.estelar.meeting_room_title')}
    span.subtitle
      | #{t('views.affiliates.estelar.meeting_room_subtitle')}
  .row.no-margin
    .col-md-10.no-padding style="margin: 0 104px;"
      .search-box.js-headline-search
        = form_tag public_affiliate_meeting_room_search_path, method: :get, class: '', "ng-controller" => "PublicAffiliateSearchCtrl", "ng-init" => "#{ng_init_for_search_form}" do

          .hidden
            input.cpy-pack-length type="text" name="by_pack_length" ng-model="selectedPackSize"
            input.cpy-room-category type="text" name="room_category" ng-model="selectedTabRoom"
            input.cpy-number-of-people type="text" name="by_number_of_people" ng-model="numberOfPeople"
            
          .tabbable
            .online_reservation_box
              p #{t('views.affiliates.estelar.book_online')}
            .tab-content-custom
              = render partial: "/layouts/public_affiliate/personalized_affiliate/#{layout_name}/meeting_room/search_form_content"

app/views/layouts/public_affiliate/personalized_affiliate/estelar/meeting_room/_search_form_header.html.slim
ruby:
  # we must keep in here because there are some controllers in the public area that doen'st inherit from public::base
  ng_init_for_search_form = if last_search_log
    # 0 - day
    # 1 - month
    # 2 - year
    date_parts = last_search_log.checkin_date.split("/")
    english_date_format = "#{date_parts[1]}/#{date_parts[0]}/#{date_parts[2]}"
    checkout_hour = last_search_log.checkin_hour + last_search_log.length_of_pack
    if checkout_hour >= 24
      checkout_hour -= 24
    end
    %Q{
      latitude = '#{last_search_log.latitude}';
      longitude = '#{last_search_log.longitude}';
      checkinDate = '#{I18n.locale == :en ? english_date_format : last_search_log.checkin_date}';
      parsedSelectedCheckinDate = '#{last_search_log.checkin_date}';
      checkinHour = #{last_search_log.checkin_hour};
      numberOfPeople = #{last_search_log.number_of_people};
      selectedPackSize = '#{last_search_log.length_of_pack}';
      cityName = '#{last_search_log.city_name}';
      stateName = '#{last_search_log.state_name}';
      address = '#{last_search_log.address}';
      selectedTabRoom = '#{last_search_log.room_category || 1}';
      checkoutHour = #{checkout_hour};
      setLatitudeAndLongitudeValidity();
    }.squish
  else
    ""
  end


= form_tag public_affiliate_meeting_room_search_path, method: :get, class: '', "ng-controller" => "PublicAffiliateSearchCtrl", "ng-init" => "#{ng_init_for_search_form}" do

  .hidden
    input.cpy-city-name type='text' ng-model="cityName" name='city_name'
    input.cpy-state-name type='text' ng-model="stateName" name='state_name'
    input.cpy-latitude-field type="text" name="by_latitude" ng-model='latitude'
    input.cpy-longitude-field type="text" name="by_longitude" ng-model='longitude'
    input.cpy-pack-length type="text" name="by_pack_length" ng-model="selectedPackSize"
    input.cpy-room-category type="text" name="room_category" ng-model="selectedTabRoom"
    input.cpy-address type="text" name="by_address" ng-model="address"
    input.cpy-number-of-people type="text" name="by_number_of_people" ng-model="numberOfPeople"

  .col-xs-12.hidden-xs style="position: relative; padding: 0px"
    .gradient_overlay
    .image-room-category
      .js-float-search-form
        = render partial: "/layouts/public_affiliate/personalized_affiliate/#{layout_name}/meeting_room/search_form_content"

app/views/layouts/public_affiliate/personalized_affiliate/estelar/meeting_room/_search_form_hotel_header.html.slim
ruby:
  # we must keep in here because there are some controllers in the public area that doen'st inherit from public::base
  ng_init_for_search_form = if last_search_log
    # 0 - day
    # 1 - month
    # 2 - year
    date_parts = last_search_log.checkin_date.split("/")
    english_date_format = "#{date_parts[1]}/#{date_parts[0]}/#{date_parts[2]}"
    checkout_hour = last_search_log.checkin_hour + last_search_log.length_of_pack
    if checkout_hour >= 24
      checkout_hour -= 24
    end
    %Q{
      latitude = '#{last_search_log.latitude}';
      longitude = '#{last_search_log.longitude}';
      checkinDate = '#{I18n.locale == :en ? english_date_format : last_search_log.checkin_date}';
      parsedSelectedCheckinDate = '#{last_search_log.checkin_date}';
      checkinHour = #{last_search_log.checkin_hour};
      numberOfPeople = #{last_search_log.number_of_people};
      selectedPackSize = '#{last_search_log.length_of_pack}';
      cityName = '#{last_search_log.city_name}';
      stateName = '#{last_search_log.state_name}';
      address = '#{last_search_log.address}';
      selectedTabRoom = '#{last_search_log.room_category || 3}';
      checkoutHour = #{checkout_hour};
      setLatitudeAndLongitudeValidity();
    }.squish
  else
    ""
  end
= form_tag public_affiliate_hotels_path, method: :get, class: '', "ng-controller" => "PublicAffiliateSearchCtrl", "ng-init" => "#{ng_init_for_search_form}" do

  .hidden
    input.cpy-city-name type='text' ng-model="cityName" name='city_name'
    input.cpy-state-name type='text' ng-model="stateName" name='state_name'
    input.cpy-latitude-field type="text" name="by_latitude" ng-model='latitude'
    input.cpy-longitude-field type="text" name="by_longitude" ng-model='longitude'
    input.cpy-pack-length type="text" name="by_pack_length" ng-model="selectedPackSize"
    input.cpy-room-category type="text" name="room_category" ng-model="selectedTabRoom"
    input.cpy-address type="text" name="by_address" ng-model="address"
    input.cpy-number-of-people type="text" name="by_number_of_people" ng-model="numberOfPeople"
    input.cpy-hotel-id type="text" name="hotel_id" value="#{@hotel.id}"

  .col-xs-12.hidden-xs style="position: relative; padding: 0px"
    .search-form-hotel
      = render partial: "/layouts/public_affiliate/personalized_affiliate/#{layout_name}/meeting_room/search_form_hotel_content"

app/views/layouts/public_affiliate/personalized_affiliate/estelar/meeting_room/_with_exact_match_offers.html.slim
.row
  .col-sm-12.border-box.with-padding-bottom
    .row
      .col-sm-12
        p.pack-size
          => t(:pack_of)
          span.big => params[:length_of_pack]
          = t(:hours)
        h4.text-center
          = "#{l(params[:checkin_date].to_date)} #{t(:at)} #{convert_checkin_hour_to_am_pm(params[:checkin_date], params[:checkin_hour])}"
        p.beware.text-center
          | #{ t :beware}:
          - if @hotel.accepts_booking_cancellation?
            - date_parsed = params[:checkin_date].to_date + params[:checkin_hour].to_i.hours - @hotel.minimum_hours_of_notice.hours
            - day_of_notice = l(date_parsed)
            = t(:hotel_minimum_hours_of_notice, day_of_notice: calculate_cancelation_date(params[:checkin_date].to_date, params[:checkin_hour].to_i.hours))

          table.table.table-striped.table-hover
            thead
              th.size-5-percent
              th.size-60-percent = t :room_type
              th.size-25-percent = t :price
              th.size-10-percent
            tbody
              - @search_exact_match.each do | search_row |
                tr
                  td style="padding: 8px 4px 8px 12px"
                    - offer = search_row[:min_offer]
                    - room_type = search_row[:room_type]
                    = link_to "", public_affiliate_hotel_room_type_show_path(hotel_id: @hotel.id, hotel_name: @hotel.name.parameterize, id: room_type.id, length_of_pack: params[:length_of_pack], checkin_date: params[:checkin_date], checkin_hour: params[:checkin_hour], number_of_people: params[:number_of_people], offer_price: total_price_for_number_of_people(params[:number_of_people], offer)), class: "glyphicon glyphicon-question-sign big", "data-toggle" => "modal", "data-target" => ".js-room-type-modal", remote: true
                  td.js-room-type-description
                    = room_type.send("full_name_#{I18n.locale}")
                  td.bigger.js-room-type-description
                     = number_to_currency(calculate_currency(total_price_for_number_of_people(params[:number_of_people], offer), Hotel::CURRENCY_SYMBOL_REVERSED[@hotel.currency_symbol]).round, unit: current_currency.money_sign, precision: 0)
                  td.js-room-type-description
                    - if can_current_public_affiliate_user_afford?(price_without_tax: offer.price.to_f, pack_in_hours: params[:length_of_pack])
                      = link_to t(:reserve), new_public_affiliate_booking_path(price: offer.price, checkin_timestamp: (params[:checkin_date].to_datetime + params[:checkin_hour].to_i.hours).strftime("%Y-%m-%d %H:%M:%S +0000"), pack_in_hours: params[:length_of_pack], room_type_id: offer.room_type_id, number_of_people: params[:number_of_people]), class: "pill btn-success small cpy-reserve-offer-button hidden-sm hidden-xs"
                      = link_to "<i class='fa fa-angle-right'></i>".html_safe, new_public_affiliate_booking_path(price: offer.price, checkin_timestamp: (params[:checkin_date].to_datetime + params[:checkin_hour].to_i.hours).strftime("%Y-%m-%d %H:%M:%S +0000"), pack_in_hours: params[:length_of_pack], room_type_id: offer.room_type_id, number_of_people: params[:number_of_people]), class: "js-new-booking arrow-right btn-success cpy-reserve-offer-mobile-button hidden-md hidden-lg"

          p.hint
            => t :click_on_the_icon
            span.glyphicon.glyphicon-question-sign
            =<   t :to_see_more_details_about_the_room_type
        - if @similar_offers_found
          .row
            .col-sm-12
              a.btn.btn-success.js-scroll-button.scroll-button href='#similar-offers'
                => t(:see_similar_offers)
                i.glyphicon.glyphicon-arrow-down

    .row.hidden-md.hidden-lg
      .col-sm-12
        #map-canvas-mobile[style="width:100%; height:400px"]