config/routes.rb
# encoding: utf-8
require 'sidekiq/web'

Rails.application.routes.draw do

  localized do
    namespace :admin, path_names: { new: 'novo', create: 'novo', edit: 'editar', update: 'editar', remove: 'remover', deactivate: 'desativar'} do

      root :to => 'hotels#index'

      get 'mudar-senha' => 'info#edit', as: :change_password

      patch 'mudar-senha' => 'info#update_password'

      devise_for :managers,
           controllers: { sessions:           'admin/sessions',
                          passwords:          'admin/passwords'
                        },
           path: '/', path_names:{
                                  sign_in: 'entrar',
                                  sign_out: 'sair'
                                 }

      resources :users, path: 'usuarios', only: [:index, :show, :edit, :update]

      resources :emkts, path: 'emkt' do
        collection do
          get :with_bookings
          get :without_bookings
        end
      end

      resources :offers, path: 'ofertas', only: [:index]

      resources :hotel_search_logs, path: 'logs-de-busca', only: [:index]

      get '/usuarios/detalhes_da_reserva/:id', to: 'users#user_booking_show', as: 'user_booking_show'

      resources :payments, path: 'pagamentos', only: [:index, :show]

      resources :bookings, path: 'reservas', only: [:index, :show] do
        member do
          put :cancel
          put :hotel_accept_request
          put :hotel_deny_request
          post :send_confirmation_notice_email
        end
      end

      get 'relatorios' => 'hotel_reports#index', as: :hotel_reports

      get 'relatorios-agencias' => 'agency_reports#index', as: :agency_reports

      resources :campaigns, path: 'campanhas'

      resources :promotional_codes, path: 'codigos-promocionais'

      resources :newsletters, path: 'newsletters', only: [:index] do
        collection do
          get   :import
          post :import_csv
        end
      end

      resources :states, path: 'cidades-e-estados',  except: [:destroy, :show]

      resources :cities, path: 'cidades',  only: [:new, :create]

      resources :booking_packs, path: 'banco-de-horas',  except: [:destroy]

      resources :booking_pack_contracting_companies, path: 'empresas-contratantes', only: [:index, :show]

      resources :booking_taxes, path: 'taxas', only: [:index, :edit, :update]

      resources :company_details, path: 'empresas', only: [:index, :show, :edit, :update] do
      end

      resources :possible_partner_contacts, path: 'contatos-de-possiveis-parceiros', only: [:index, :show] do
        collection do
          put :mark_all_messages_as_read
        end
      end

      resources :managers, path: 'managers', except: [:destroy] do
        member do
          post :deactivate
          post :activate
        end
      end

      resources :agencies, path: 'agencias', except: [:destroy] do
        member do
          post :deactivate
          post :activate
        end
      end

      resources :affiliates, path: 'afiliados', except: [:destroy] do
        member do
          post :deactivate
          post :activate
          post :generate_token
          post :generate_webservice_token
        end
      end

      resources :member_get_member_config, path: 'member_get_member_config', only: [:show, :edit, :update] 
  

      resources :devices, path: 'dispositivos', only: [:index, :destroy]

    resources :hotel_chains, path: 'redes-hoteleiras'

    resources :hotels, path: 'hoteis', :except => [:destroy] do
      resources :room_types, path: 'tipos-de-quartos', controller: 'hotels/room_types', except: [:destroy, :index, :new, :create]
      resources :meeting_rooms, path: 'salas-de-reuniao', controller: 'hotels/meeting_rooms', except: [:destroy, :index, :new, :create]
      #resources :event_rooms, path: 'saloes-de-evento', controller: 'hotels/event_rooms', except: [:destroy, :index, :new, :create]

        member do
          get :authenticate_as
        end

        scope '/quartos' do
          #get '/tabelas-de-precos/:id', to: 'hotels/pricing_policies#show', as: :pricing_policy
          resources :pricing_policies, path: 'tabelas-de-precos', controller: 'hotels/pricing_policies', except: [:destroy, :index, :new, :create]
          get '/menor-preco-por-pacote', to: 'hotels/minimum_offers_price#show', as: :minimum_offers_price_show
        end

        scope '/salas-de-reuniao' do
          get '/tabelas-de-precos/:id', to: 'hotels/pricing_policies#meeting_show', as: :meeting_room_pricing_policy
          get '/menor-preco-por-pacote', to: 'hotels/minimum_offers_price#meeting_show', as: :minimum_meeting_offers_price_show
        end

        #scope '/saloes-de-evento' do
        #  get '/tabelas-de-precos/:id', to: 'hotels/pricing_policies#event_show', as: :event_room_pricing_policy
        #  get '/menor-preco-por-pacote', to: 'hotels/minimum_offers_price#event_show', as: :minimum_event_offers_price_show
        #end

      end

      get 'codus/objects' => 'codus#objects_list'

      resources :currencies, path: 'moedas' do
        collection do
          get :update_all
        end
      end

      resources :places, except: [:index], path: 'lugares' do
        collection do
          post :activate
          post :deactivate
          get :airports
          get :cities
          get :regions
        end
      end


      resources :executive_responsibles, path: 'universo-de-empresas/executivos' do
        member do
          post :activate
          post :deactivate
        end
      end

      resources :company_attendants, path: 'universo-de-empresas/atendimento-empresas' do
        member do
          post :activate
          post :deactivate
        end
      end

      resources :company_regions, path: 'universo-de-empresas/regioes' do
        member do
          post :activate
          post :deactivate
        end
      end

      resources :company_universes, path: 'universo-de-empresas/empresas' do
        member do
          post :activate
          post :deactivate
        end
      end

      resources :company_remunerations, except: [:create, :new] , path: 'universo-de-empresas/remuneracao' do
      end

      resources :goals_executive_responsibles,  only: [:index, :show], except: [:create, :new, :edit], path: 'universo-de-empresas/metas-executivos' do
      end

      resources :hq_consultants, path: 'consultores' do
        member do
          post :activate
          post :deactivate
        end
      end

    end # of admin namespace
  end

  namespace :agency, path: 'agencias', path_names: { new: 'novo', create: 'novo', edit: 'editar', update: 'editar' } do
    root to: 'info#index'

    devise_for :agencies, path: '/', path_names:{
                                                  sign_in: 'entrar',
                                                  sign_out: 'sair'
                                                }

    get 'mudar-senha' => 'info#edit', as: :change_password

    patch 'mudar-senha' => 'info#update_password'

    get 'relatorio-de-reservas' => 'bookings_report#index', as: :bookings_report
    post 'relatorio-de-reservas' => 'bookings_report#index', as: :generate_bookings_report

    resources :clients, except: [:destroy ], path: 'clientes' do
      member do
        post :authenticate_as_client_employee, path: 'funcionario/:employee_id/acessar-como'
        post :authenticate_as_client, path: 'acessar-como'
      end
    end

    resources :bookings, only: [ :index, :show ], path: 'reservas' do
      member do
        put :cancel
      end
    end
  end # of agency namespace

  namespace :executive_responsible, path: 'executivos', path_names: { new: 'novo', create: 'novo', edit: 'editar', update: 'editar' } do
    root to: 'dashboard#index'

    devise_for :executive_responsibles,
                  controllers: {
                              sessions:           'executive_responsible/sessions',
                              passwords:          'executive_responsible/passwords'
                            },
                  path: '/', path_names:{
                                        sign_in: 'entrar',
                                        sign_up: 'registrar',
                                        sign_out: 'sair'
                                       }

    get 'mudar-senha' => 'info#edit', as: :change_password

    patch 'mudar-senha' => 'info#update_password'

    resources :company_details, path: '/empresas' do
      member do
        get :authenticate_as
      end
    end

    resources :company_regions, path: 'universo-de-empresas/regioes' do
      collection do
        post :activate
        post :deactivate
      end
    end

    resources :company_universes, path: 'universo-de-empresas/empresas' do
      collection do
        get  :all_companies, path: 'todas-empresas'
        post :activate
        post :deactivate
      end
    end


    resources :bookings, path: 'reservas', only: [:index, :show] do
      member do
        put :cancel
        put :hotel_accept_request
        put :hotel_deny_request
      end
    end


  end # of executive_responsible namespace


  namespace :hq_consultant, path: 'consultor', path_names: { new: 'novo', create: 'novo', edit: 'editar', update: 'editar' }  do
    root to: 'travel_requests#index'

    devise_for :hq_consultants,
                  controllers: {
                              sessions:           'hq_consultant/sessions',
                              passwords:          'hq_consultant/passwords'
                            },
                  path: '/', path_names:{
                                        sign_in: 'entrar',
                                        sign_up: 'registrar',
                                        sign_out: 'sair'
                                       }

    get 'mudar-senha' => 'info#edit', as: :change_password

    patch 'mudar-senha' => 'info#update_password'

app/controllers/admin/bookings_controller.rb
# encoding: utf-8
class Admin::BookingsController < Admin::BaseController
  actions :index, :show, :send_confirmation_notice_email
  before_filter :check_colombian_authorization, :only => [:show, :edit, :cancel]
  include Admin::BaseHelper
  has_scope :by_checkin_date, using: [:initial_date, :final_date]
  has_scope :by_created_at, using: [:initial_date, :final_date]
  has_scope :by_status
  has_scope :by_pack_length, type: :array
  has_scope :by_guest_name
  has_scope :by_hotel_id
  has_scope :by_id
  has_scope :by_actual_month
  has_scope :by_last_month
  has_scope :by_delayed_month
  has_scope :by_checkout_delay
  has_scope :by_refund_error
  has_scope :by_agency_creation
  has_scope :by_multiplus_code
  has_scope :by_meeting_room_offer
  has_scope :by_event_room_offer
  has_scope :by_room_offer
  has_scope :by_user_id
  before_action :set_booking, only: [:hotel_accept_request, :hotel_deny_request]

  def index
    case params[:commit]
    when t("views.admin.bookings.export_data")
      send_data(BookingsReport.new(collection.per(500)).export.to_stream.read,
        filename: "reserva_#{Time.now.strftime('%m%d%Y%k%M%S')}.xlsx",
        type:     "application/xlsx")
    else
      @booking_count = apply_scopes(Booking).order('id DESC').count
      super
    end
  end

  def send_confirmation_notice_email
    @booking = Booking.find(params[:id])
    if params[:commit] == t("views.admin.bookings.send_confirmation_notice_mail_to_hotel")
      HotelMailer.send_booking_confirmation_notice(@booking).deliver
      flash[:notice] = t("views.admin.bookings.email_sent_to_hotel", hotel_name: @booking.hotel.name)
    elsif params[:commit] == t("views.admin.bookings.send_confirmation_notice_mail_to_user")
      UserMailer.send_booking_confirmation_notice(@booking).deliver
      flash[:notice] = t("views.admin.bookings.email_sent_to_user", user_name: @booking.user.name)
    end
    redirect_to admin_booking_path(@booking)
  end

  def cancel
    @booking = Booking.find(params[:id])

    booking_cancellation_response = BookingCancellationSrv.call(booking: @booking, admin_cancelation: true)
    if booking_cancellation_response.success
      flash[:notice] = booking_cancellation_response.message
    else
      flash[:error] = booking_cancellation_response.message
    end

    redirect_to admin_bookings_path
  end

  def hotel_accept_request
    if @booking.status == Booking::ACCEPTED_STATUSES[:requested_reservation]
      @booking.status = Booking::ACCEPTED_STATUSES[:confirmed]
    elsif @booking.status == Booking::ACCEPTED_STATUSES[:requested_and_paid_reservation]
      @booking.status = Booking::ACCEPTED_STATUSES[:confirmed_and_invoiced]
    end
    @booking.save! if @booking.valid?
    UserMailer.booking_request_accepted(@booking).deliver
    redirect_to admin_bookings_path
  end

  def hotel_deny_request
    @booking.status = Booking::ACCEPTED_STATUSES[:canceled]
    @booking.save! if @booking.valid?
    UserMailer.booking_request_denied(@booking).deliver
    redirect_to admin_bookings_path
  end

  private
  def check_colombian_authorization
    booking = Booking.find(params[:id])
    if current_admin_manager.master? && current_admin_manager.country == "CO" && booking.user.country != 'CO'
      redirect_to admin_bookings_path
    end
  end

  protected

    def collection
      if current_admin_manager.country == "BR"
        @bookings ||= end_of_association_chain.order('id DESC').page(params[:page]).per(40)
      else
        @bookings ||= end_of_association_chain.joins(:user).where('users.country' => current_admin_manager.country).order('id DESC').page(params[:page]).per(40)
      end
    end

    def set_booking
      @booking = Booking.find_by id: params[:id]
    end

end

app/controllers/affiliate/bookings_controller.rb
# encoding: utf-8
class Affiliate::BookingsController < Affiliate::BaseController
  has_scope :by_checkin_date, using: [:initial_date, :final_date]
  has_scope :by_pack_length, type: :array
  has_scope :by_hotel_id
  has_scope :by_id

  def cancel
    @booking = current_affiliate_affiliate.bookings.find(params[:id])
    booking_cancellation_response = BookingCancellationSrv.call(booking: @booking, agency_cancelation: true)

    if booking_cancellation_response.success
      flash[:notice] = booking_cancellation_response.message
    else
      flash[:error] = booking_cancellation_response.message
    end

    redirect_to affiliate_booking_path(@booking)
  end

  private
    def collection
      @bookings ||= end_of_association_chain.includes(:user).includes(:hotel).includes(:offer).page(params[:page]).per(40)
    end
end

app/controllers/agency/bookings_controller.rb
# encoding: utf-8
class Agency::BookingsController < Agency::BaseController
  actions :index, :show
  has_scope :by_id
  has_scope :by_status
  has_scope :by_company_id
  has_scope :by_checkin_date, using: [:initial_date, :final_date]
  has_scope :by_checkout_date, using: [:initial_date, :final_date]

  def cancel
    @booking = current_agency_agency.bookings.where(created_by_agency: true).find(params[:id])

    booking_cancellation_response = BookingCancellationSrv.call(booking: @booking, agency_cancelation: true)
    if booking_cancellation_response.success
      flash[:notice] = booking_cancellation_response.message
    else
      flash[:error] = booking_cancellation_response.message
    end

    redirect_to agency_bookings_path
  end

  protected
    def end_of_association_chain
      association_chain = super
      return association_chain.where(created_by_agency: true)
    end

    def collection
      @bookings ||= end_of_association_chain.order('checkin_date DESC').includes(:hotel).includes(:company).page(params[:page]).per(40)
    end

end

app/controllers/company/bookings_controller.rb
# encoding: utf-8
class Company::BookingsController < Company::BaseController
  has_scope :by_checkin_date, using: [:initial_date, :final_date]
  has_scope :by_pack_length, type: :array
  has_scope :by_hotel_id
  has_scope :by_user_id

  def cancel
    @booking = current_company_company.bookings.find(params[:id])
    booking_cancellation_response = BookingCancellationSrv.call(booking: @booking, agency_cancelation: true)

    if booking_cancellation_response.success
      flash[:notice] = booking_cancellation_response.message
    else
      flash[:error] = booking_cancellation_response.message
    end

    redirect_to company_booking_path(@booking)
  end

  private
    def collection
      @bookings ||= end_of_association_chain.includes(:user).includes(:hotel).includes(:offer).page(params[:page]).per(40)
    end
end

app/views/hotel/bookings/show/_room.html.slim
ruby:
  initial_price = @booking.promotional_code_log.present? ? @booking.initial_price_with_discount : @booking.initial_price
  extra_people_price = @booking.promotional_code_log.present? ? @booking.extra_people_price_with_discount : @booking.extra_people_price
  total_price = @booking.promotional_code_log.present? || @booking.using_balance ? @booking.total_price_without_tax_and_without_discount : @booking.total_price_without_tax
  no_show_value = @booking.no_show_value_without_tax
  user_payment_unit = Currency.by_code_or_money_sign(Hotel::CURRENCY_SYMBOL_REVERSED[@booking.hotel.currency_symbol]) if @booking.currency_code != Hotel::CURRENCY_SYMBOL_REVERSED[@booking.hotel.currency_symbol] && @booking.payments.authorized_or_captured.exists?
  authorized_or_captured_payment = @booking.payments.authorized_or_captured.order(created_at: :desc).first.authorized_at if user_payment_unit

.row
  .col-sm-6
    h3.center.header.lighter.green
      | #{t('views.hotel.bookings.general_information')}
    .attributes-wrapper.booking_status
      .attribute-title
        | #{t('views.hotel.bookings.status')}
      .content.js-booking-status.cpy-booking-status
        = t(Booking::ACCEPTED_STATUS_REVERSED[@booking.status])
    = u.attribute :guest_name
    = u.attribute :guest_email
    = u.attribute :number_of_people
    hr
    .attributes-wrapper.booking_room_type
      .attribute-title
        | #{t('views.hotel.bookings.room_type')}
      .content
        = @booking.room_type.name_pt_br
    .attributes-wrapper.booking_room_number
      .attribute-title
        | #{t('views.hotel.bookings.room_number')}
      .content
        = @booking.room.number
    .attributes-wrapper.booking_pack_size
      .attribute-title
        | #{t('views.hotel.bookings.package_size')}
      .content
        = "#{@booking.pack_in_hours}h"
    hr
    .attributes-wrapper.booking_checkin
      .attribute-title
        | #{t('views.hotel.bookings.checkin')}
    .attributes-wrapper.booking_checkin_date
      .attribute-title
        | #{t('views.hotel.bookings.date')}
      .content
        = "#{(@booking.date_interval.first + Offer::ROOM_CLEANING_TIME - 1.minute).strftime("%d/%m/%Y")}"
    .attributes-wrapper.booking_checkin_hour
      .attribute-title
        | #{t('views.hotel.bookings.hour')}
      .content
        = "#{(@booking.date_interval.first + Offer::ROOM_CLEANING_TIME - 1.minute).strftime("%H:%M")}"
    hr
    .attributes-wrapper.booking_checkout
      .attribute-title
        | #{t('views.hotel.bookings.checkout')}
    .attributes-wrapper.booking_checkout_date
      .attribute-title
        | #{t('views.hotel.bookings.date')}
      .content
        = "#{(@booking.date_interval.last - Offer::ROOM_CLEANING_TIME + 1.minute).strftime("%d/%m/%Y")}"
    .attributes-wrapper.booking_checkout_hour
      .attribute-title
        | #{t('views.hotel.bookings.hour')}
      .content
        = "#{(@booking.date_interval.last - Offer::ROOM_CLEANING_TIME + 1.minute).strftime("%H:%M")}"
    hr
    = u.attribute :note

  .col-sm-6
    - user = @booking.user
    h3.center.header.lighter.green
      | #{t('views.hotel.bookings.user_info')}

    .attributes-wrapper.booking_user_name
      .attribute-title
        | #{t('views.hotel.bookings.name')}
      .content
        = user.name
    .attributes-wrapper.booking_user_name
      .attribute-title
        | #{t('views.hotel.bookings.email')}
      .content
        = user.email
    .attributes-wrapper.booking_user_name
      .attribute-title
        | #{t('views.hotel.bookings.phone')}
      .content
        = user.phone_number
    .attributes-wrapper.booking_user_name
      .attribute-title
        | #{t('views.hotel.bookings.date_and_hour_of_reservation')}
      .content
        = l @booking.created_at
    - if @booking.status == Booking::ACCEPTED_STATUSES[:confirmed] || (@booking.status == Booking::ACCEPTED_STATUSES[:confirmed_and_captured]) || (@booking.status == Booking::ACCEPTED_STATUSES[:confirmed_and_invoiced]) || (@booking.status == Booking::ACCEPTED_STATUSES[:confirmed_without_card])
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.date_and_hour_of_confirmation')}
        .content
          = l @booking.updated_at
    - if @booking.status == Booking::ACCEPTED_STATUSES[:requested_reservation] || (@booking.status == Booking::ACCEPTED_STATUSES[:requested_and_paid_reservation])
      .attributes-wrapper.booking_user_name
        .attribute-title
          | Reserva solicitada
        .content
          = l @booking.created_at
    h3.center.header.lighter.green
      | #{t('views.hotel.bookings.values')}
    /.attributes-wrapper.booking_user_name
      .attribute-title
        | #{t('views.hotel.bookings.initial_value')}
      .content
        = number_to_currency(initial_price)
    /.attributes-wrapper.booking_user_name
      .attribute-title
        | #{t('views.hotel.bookings.total_per_extra_person')}
      .content
        = number_to_currency(extra_people_price)
    /- unless @booking.booking_tax.zero?
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.reservation_tax')}
        .content
          = number_to_currency(@booking.booking_tax)
    .attributes-wrapper.booking_user_name
      .attribute-title
        | #{t('views.hotel.bookings.total_value')}
      .content
        = number_to_currency(total_price, unit: Hotel::CURRENCY_SYMBOL_REVERSED[@booking.hotel.currency_symbol])

    - if @booking.have_discount_in_offer_price?
      .attributes-wrapper.booking_user_name
        .attribute-title
          | Desconto promocional HotelQuando
        .content
          = number_to_currency(@booking.promotional_code_log.promotional_code.discount, unit: Hotel::CURRENCY_SYMBOL_REVERSED[@booking.hotel.currency_symbol])
      .attributes-wrapper.booking_user_name
        .attribute-title
          | Valor que hospede paga no balcão
        .content
          = number_to_currency(@booking.total_price_without_tax, unit: Hotel::CURRENCY_SYMBOL_REVERSED[@booking.hotel.currency_symbol])

    - if @booking.invoice
      h3.center.header.lighter.green
        | #{t('views.hotel.bookings.nf_data')}
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.cnpj')}
        .content
          = @booking.invoice.cnpj
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.company_name')}
        .content
          = @booking.invoice.company_name
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.street')}
        .content
          = @booking.invoice.street
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.number')}
        .content
          = @booking.invoice.number
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.complement')}
        .content
          = @booking.invoice.complement
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.neighborhood')}
        .content
          = @booking.invoice.district
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.city')}
        .content
          = @booking.invoice.city
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.city')}
        .content
          = @booking.invoice.state
      .attributes-wrapper.booking_user_name
        .attribute-title
          | #{t('views.hotel.bookings.zipcode')}
        .content
          = @booking.invoice.cep

    - if @booking.status == Booking::ACCEPTED_STATUSES[:requested_reservation] || (@booking.status == Booking::ACCEPTED_STATUSES[:requested_and_paid_reservation])
      .booking-actions.js-booking-actions
        h3.center.header.lighter.green
          | #{t('views.hotel.bookings.options')}
        .text-center
          = link_to 'Aceitar', hotel_accept_request_hotel_booking_path(id: @booking.id), class: "btn btn-sm btn-danger cpy-set-as-no-show-button js-set-as-no-show-button", method: :put
          = link_to 'Recusar', hotel_deny_request_hotel_booking_path(id: @booking.id), class: "btn btn-sm btn-warning cpy-accuse-delayed-checkout-button js-set-as-no-show-button", method: :put

    - if (@booking.can_be_set_as_no_show? || @booking.can_accuse_delayed_checkout?) && !(@booking.guest_delayed_checkout?) && @booking.hotel.is_brazilian
      .booking-actions.js-booking-actions
        h3.center.header.lighter.green
          | #{t('views.hotel.bookings.options')}
        .text-center
          - if @booking.can_be_set_as_no_show?
            = link_to t('views.hotel.bookings.set_as_no_show'), set_as_no_show_hotel_booking_path(@booking.id), class: "btn btn-sm btn-danger cpy-set-as-no-show-button js-set-as-no-show-button", method: :put, remote: true, data: { confirm: t('views.hotel.bookings.set_as_no_show_confirm') }
          - if @booking.can_accuse_delayed_checkout?
            = link_to t('views.hotel.bookings.set_late_checkout'), accuse_delayed_checkout_hotel_booking_path(@booking.id), class: "btn btn-sm btn-warning cpy-accuse-delayed-checkout-button js-set-as-no-show-button", method: :put, remote: true, data: { confirm: t('views.hotel.bookings.set_late_checkout_confirm') }

      .booking-action-result.alert.js-alert.cpy_ajax_end display="none"

    - if @booking.guest_delayed_checkout?
      hr
      .attributes-wrapper.text-center
        h4
          | #{t('views.hotel.bookings.user_late_checkout')}