config/routes.rb
# encoding: utf-8
require 'sidekiq/web'

Rails.application.routes.draw do

  localized do
    namespace :admin, path_names: { new: 'novo', create: 'novo', edit: 'editar', update: 'editar', remove: 'remover', deactivate: 'desativar'} do

      root :to => 'hotels#index'

      get 'mudar-senha' => 'info#edit', as: :change_password

      patch 'mudar-senha' => 'info#update_password'

      devise_for :managers,
           controllers: { sessions:           'admin/sessions',
                          passwords:          'admin/passwords'
                        },
           path: '/', path_names:{
                                  sign_in: 'entrar',
                                  sign_out: 'sair'
                                 }

      resources :users, path: 'usuarios', only: [:index, :show, :edit, :update]

      resources :emkts, path: 'emkt' do
        collection do
          get :with_bookings
          get :without_bookings
        end
      end

      resources :offers, path: 'ofertas', only: [:index]

      resources :hotel_search_logs, path: 'logs-de-busca', only: [:index]

      get '/usuarios/detalhes_da_reserva/:id', to: 'users#user_booking_show', as: 'user_booking_show'

      resources :payments, path: 'pagamentos', only: [:index, :show]

      resources :bookings, path: 'reservas', only: [:index, :show] do
        member do
          put :cancel
          put :hotel_accept_request
          put :hotel_deny_request
          post :send_confirmation_notice_email
        end
      end

      get 'relatorios' => 'hotel_reports#index', as: :hotel_reports

      get 'relatorios-agencias' => 'agency_reports#index', as: :agency_reports

      resources :campaigns, path: 'campanhas'

      resources :promotional_codes, path: 'codigos-promocionais'

      resources :newsletters, path: 'newsletters', only: [:index] do
        collection do
          get   :import
          post :import_csv
        end
      end

      resources :states, path: 'cidades-e-estados',  except: [:destroy, :show]

      resources :cities, path: 'cidades',  only: [:new, :create]

      resources :booking_packs, path: 'banco-de-horas',  except: [:destroy]

      resources :booking_pack_contracting_companies, path: 'empresas-contratantes', only: [:index, :show]

      resources :booking_taxes, path: 'taxas', only: [:index, :edit, :update]

      resources :company_details, path: 'empresas', only: [:index, :show, :edit, :update] do
      end

      resources :possible_partner_contacts, path: 'contatos-de-possiveis-parceiros', only: [:index, :show] do
        collection do
          put :mark_all_messages_as_read
        end
      end

      resources :managers, path: 'managers', except: [:destroy] do
        member do
          post :deactivate
          post :activate
        end
      end

      resources :agencies, path: 'agencias', except: [:destroy] do
        member do
          post :deactivate
          post :activate
        end
      end

      resources :affiliates, path: 'afiliados', except: [:destroy] do
        member do
          post :deactivate
          post :activate
          post :generate_token
          post :generate_webservice_token
        end
      end

      resources :member_get_member_config, path: 'member_get_member_config', only: [:show, :edit, :update] 
  

      resources :devices, path: 'dispositivos', only: [:index, :destroy]

    resources :hotel_chains, path: 'redes-hoteleiras'

    resources :hotels, path: 'hoteis', :except => [:destroy] do
      resources :room_types, path: 'tipos-de-quartos', controller: 'hotels/room_types', except: [:destroy, :index, :new, :create]
      resources :meeting_rooms, path: 'salas-de-reuniao', controller: 'hotels/meeting_rooms', except: [:destroy, :index, :new, :create]
      #resources :event_rooms, path: 'saloes-de-evento', controller: 'hotels/event_rooms', except: [:destroy, :index, :new, :create]

        member do
          get :authenticate_as
        end

        scope '/quartos' do
          #get '/tabelas-de-precos/:id', to: 'hotels/pricing_policies#show', as: :pricing_policy
          resources :pricing_policies, path: 'tabelas-de-precos', controller: 'hotels/pricing_policies', except: [:destroy, :index, :new, :create]
          get '/menor-preco-por-pacote', to: 'hotels/minimum_offers_price#show', as: :minimum_offers_price_show
        end

        scope '/salas-de-reuniao' do
          get '/tabelas-de-precos/:id', to: 'hotels/pricing_policies#meeting_show', as: :meeting_room_pricing_policy
          get '/menor-preco-por-pacote', to: 'hotels/minimum_offers_price#meeting_show', as: :minimum_meeting_offers_price_show
        end

        #scope '/saloes-de-evento' do
        #  get '/tabelas-de-precos/:id', to: 'hotels/pricing_policies#event_show', as: :event_room_pricing_policy
        #  get '/menor-preco-por-pacote', to: 'hotels/minimum_offers_price#event_show', as: :minimum_event_offers_price_show
        #end

      end

      get 'codus/objects' => 'codus#objects_list'

      resources :currencies, path: 'moedas' do
        collection do
          get :update_all
        end
      end

      resources :places, except: [:index], path: 'lugares' do
        collection do
          post :activate
          post :deactivate
          get :airports
          get :cities
          get :regions
        end
      end


      resources :executive_responsibles, path: 'universo-de-empresas/executivos' do
        member do
          post :activate
          post :deactivate
        end
      end

      resources :company_attendants, path: 'universo-de-empresas/atendimento-empresas' do
        member do
          post :activate
          post :deactivate
        end
      end

      resources :company_regions, path: 'universo-de-empresas/regioes' do
        member do
          post :activate
          post :deactivate
        end
      end

      resources :company_universes, path: 'universo-de-empresas/empresas' do
        member do
          post :activate
          post :deactivate
        end
      end

      resources :company_remunerations, except: [:create, :new] , path: 'universo-de-empresas/remuneracao' do
      end

      resources :goals_executive_responsibles,  only: [:index, :show], except: [:create, :new, :edit], path: 'universo-de-empresas/metas-executivos' do
      end

      resources :hq_consultants, path: 'consultores' do
        member do
          post :activate
          post :deactivate
        end
      end

    end # of admin namespace
  end

  namespace :agency, path: 'agencias', path_names: { new: 'novo', create: 'novo', edit: 'editar', update: 'editar' } do
    root to: 'info#index'

    devise_for :agencies, path: '/', path_names:{
                                                  sign_in: 'entrar',
                                                  sign_out: 'sair'
                                                }

    get 'mudar-senha' => 'info#edit', as: :change_password

    patch 'mudar-senha' => 'info#update_password'

    get 'relatorio-de-reservas' => 'bookings_report#index', as: :bookings_report
    post 'relatorio-de-reservas' => 'bookings_report#index', as: :generate_bookings_report

    resources :clients, except: [:destroy ], path: 'clientes' do
      member do
        post :authenticate_as_client_employee, path: 'funcionario/:employee_id/acessar-como'
        post :authenticate_as_client, path: 'acessar-como'
      end
    end

    resources :bookings, only: [ :index, :show ], path: 'reservas' do
      member do
        put :cancel
      end
    end
  end # of agency namespace

  namespace :executive_responsible, path: 'executivos', path_names: { new: 'novo', create: 'novo', edit: 'editar', update: 'editar' } do
    root to: 'dashboard#index'

    devise_for :executive_responsibles,
                  controllers: {
                              sessions:           'executive_responsible/sessions',
                              passwords:          'executive_responsible/passwords'
                            },
                  path: '/', path_names:{
                                        sign_in: 'entrar',
                                        sign_up: 'registrar',
                                        sign_out: 'sair'
                                       }

    get 'mudar-senha' => 'info#edit', as: :change_password

    patch 'mudar-senha' => 'info#update_password'

    resources :company_details, path: '/empresas' do
      member do
        get :authenticate_as
      end
    end

    resources :company_regions, path: 'universo-de-empresas/regioes' do
      collection do
        post :activate
        post :deactivate
      end
    end

    resources :company_universes, path: 'universo-de-empresas/empresas' do
      collection do
        get  :all_companies, path: 'todas-empresas'
        post :activate
        post :deactivate
      end
    end


    resources :bookings, path: 'reservas', only: [:index, :show] do
      member do
        put :cancel
        put :hotel_accept_request
        put :hotel_deny_request
      end
    end


  end # of executive_responsible namespace


  namespace :hq_consultant, path: 'consultor', path_names: { new: 'novo', create: 'novo', edit: 'editar', update: 'editar' }  do
    root to: 'travel_requests#index'

    devise_for :hq_consultants,
                  controllers: {
                              sessions:           'hq_consultant/sessions',
                              passwords:          'hq_consultant/passwords'
                            },
                  path: '/', path_names:{
                                        sign_in: 'entrar',
                                        sign_up: 'registrar',
                                        sign_out: 'sair'
                                       }

    get 'mudar-senha' => 'info#edit', as: :change_password

    patch 'mudar-senha' => 'info#update_password'

app/controllers/admin/executive_responsibles_controller.rb
class Admin::ExecutiveResponsiblesController < Admin::BaseController
	before_action :authorized_master
	def create
		create! do | success, failure |
			success.html do
				GoalsExecutiveResponsible.new_goals_executive_responsible(@executive_responsible)
				ExecutiveResponsibleMailer.send_login_and_password(@executive_responsible).deliver
				redirect_to admin_executive_responsible_path(@executive_responsible)
			end
		end
	end

	def update
		build_resource_params
		update!
		GoalsExecutiveResponsible.update_goals_executive_responsible(params)
	end

	def activate
		begin
			ExecutiveResponsible.find(params[:id]).activate!
			flash['success'] = I18n.t('views.company_universe.executive_controller.activate_success')
		rescue
			flash['error'] = I18n.t('views.company_universe.executive_controller.activate_error')
		end
		redirect_to :back
	end

	def deactivate
		begin
			ExecutiveResponsible.find(params[:id]).deactivate!
			flash['success'] = I18n.t('views.company_universe.executive_controller..deactivate_success')
		rescue
			flash['error'] = I18n.t('views.company_universe.executive_controller..deactivate_error')
		end
		redirect_to :back
	end

	def build_resource_params
		[params.fetch(:executive_responsible, {}).permit!]
	end

	def collection
      @executive_responsibles ||= ExecutiveResponsible.all.page(params[:page]).per(40)
    end
end

app/controllers/executive_responsible/base_controller.rb
# encoding: utf-8
class ExecutiveResponsible::BaseController < ActionController::Base
  protect_from_forgery
  inherit_resources
  layout 'executive_responsible'
  before_filter :authenticate_executive_responsible_executive_responsible!, :set_locale, :set_locale_from_header

  protected

    def begin_of_association_chain
      current_executive_responsible_executive_responsible
    end

    def getCurrentExecutive
      return current_executive_responsible_executive_responsible
    end

    def set_locale
      unless action_name == 'timezone'
        if params[:locale] == 'pt_br' || params[:lang] == 'pt-br'
          cookies[:locale] = params[:locale]
        elsif params[:locale] == 'en' || params[:locale] == 'es'
          cookies[:locale] = params[:locale]
        else
          if cookies[:locale].blank?
            cookies[:locale] = set_locale_from_header
          end
        end
      end

      I18n.locale = I18n.available_locales.include?(cookies[:locale].try(:to_sym)) ? cookies[:locale] : I18n.default_locale
    end
    def set_locale_from_header
      request.env['HTTP_ACCEPT_LANGUAGE'].gsub! 'pt-BR', 'pt_BR' unless request.env['HTTP_ACCEPT_LANGUAGE'].blank?
      return http_accept_language.compatible_language_from(I18n.available_locales) || 'en'
    end
end

app/controllers/executive_responsible/bookings_controller.rb
# encoding: utf-8
class ExecutiveResponsible::BookingsController < ExecutiveResponsible::BaseController
  actions :index, :show, :cancel
  has_scope :by_checkin_date, using: [:initial_date, :final_date]
  has_scope :by_status
  has_scope :by_pack_length, type: :array
  has_scope :by_guest_name
  has_scope :by_hotel_id
  has_scope :by_id
  has_scope :by_actual_month
  has_scope :by_last_month
  has_scope :by_delayed_month
  has_scope :by_checkout_delay
  has_scope :by_refund_error
  has_scope :by_agency_creation
  has_scope :by_multiplus_code
  has_scope :by_meeting_room_offer
  has_scope :by_event_room_offer
  has_scope :by_room_offer
  has_scope :by_user_id
  before_action :set_booking, only: [:hotel_accept_request, :hotel_deny_request, :show]

  def index
    case params[:commit]
    when t(:export_data)
      send_data(BookingsReport.new(collection.per(500)).export.to_stream.read,
        filename: "reserva_#{Time.now.strftime('%m%d%Y%k%M%S')}.xlsx",
        type:     "application/xlsx")
    else
      super
    end
  end


  def hotel_accept_request
    if @booking.status == Booking::ACCEPTED_STATUSES[:requested_reservation]
      @booking.status = Booking::ACCEPTED_STATUSES[:confirmed]
    elsif @booking.status == Booking::ACCEPTED_STATUSES[:requested_and_paid_reservation]
      @booking.status = Booking::ACCEPTED_STATUSES[:confirmed_and_invoiced]
    end
    @booking.save! if @booking.valid?
    UserMailer.booking_request_accepted(@booking).deliver
    redirect_to admin_bookings_path
  end

  def hotel_deny_request
    @booking.status = Booking::ACCEPTED_STATUSES[:canceled]
    @booking.save! if @booking.valid?
    UserMailer.booking_request_denied(@booking).deliver
    redirect_to admin_bookings_path
  end

  def cancel
    @booking = Booking.find(params[:id])

    booking_cancellation_response = BookingCancellationSrv.call(booking: @booking, admin_cancelation: true)
    if booking_cancellation_response.success
      flash[:notice] = booking_cancellation_response.message
    else
      flash[:error] = booking_cancellation_response.message
    end

    redirect_to executive_responsible_bookings_path
  end

  private

  protected

    def collection
      @bookings ||= apply_scopes(Booking).includes(:hotel,:user,:offer,:omnibees_offer).where(user_id: (User.where(email: "affiliate_ws_api_system@hotelquando.com").last.try(:id))).order('id DESC').page(params[:page]).per(40)
    end

    def set_booking
      @booking = Booking.find_by id: params[:id]
    end

end

app/controllers/executive_responsible/company_regions_controller.rb
class ExecutiveResponsible::CompanyRegionsController < ExecutiveResponsible::BaseController

	def create
		prepare_params
		create!
	end

	def update
		prepare_params
		update!
	end

	def activate
		begin
			CompanyRegion.find(params[:id]).activate!
			flash['success'] = I18n.t('views.company_universe.region_controller.activate_success')
		rescue
			flash['error'] = I18n.t('views.company_universe.region_controller.activate_error')
		end
		redirect_to :back
	end

	def deactivate
		begin
			CompanyRegion.find(params[:id]).deactivate!
			flash['success'] = I18n.t('views.company_universe.region_controller..deactivate_success')
		rescue
			flash['error'] = I18n.t('views.company_universe.region_controller..deactivate_error')
		end
		redirect_to :back
	end

	def build_resource_params
		[params.fetch(:company_region, {}).permit!]
	end


	def prepare_params
		unless params[:citiesHash].blank?
			cities_hash = params[:citiesHash].split(', ')
			params[:company_region][:city_id]  = cities_hash[0]
		end
	end

	protected
	def end_of_association_chain
		return CompanyRegion.all
	end

	def collection
		@company_regions ||= end_of_association_chain.includes(:city).page(params[:page]).per(40)
	end

end

app/controllers/executive_responsible/passwords_controller.rb
# encoding: utf-8
class ExecutiveResponsible::PasswordsController < Devise::PasswordsController
  layout 'executive_responsible/login'

  def create
    change_login_for_email_in_params
    super
  end

  def after_resetting_password_path_for(executive)
    executive_responsible_root_path
  end

  private
  def change_login_for_email_in_params
    params[resource_name]['email'] = resource_class.find_by_login(params[resource_name]['login']).email
    params[resource_name].delete 'login'
  end
end

app/helpers/executive_responsible/base_helper.rb
# encoding: utf-8

module ExecutiveResponsible::BaseHelper
  include CodusTemplates::Helpers::AceAdmin
  include Shared::CodusHelper
  include Shared::FormHelper

  def menu_active_for(type, action = nil)
    active_in_controller = ["executive_responsible/#{type}"].include? params[:controller]
    if action.nil?
      active_in_controller ? "active" : ''
    else
      if action.is_a? Array
        active_in_action = action.map(&:to_s).include? params[:action]
      else
        active_in_action = (params[:action] == action.to_s)
      end
      (active_in_controller && active_in_action) ? "active" : ''
    end
  end
end

app/views/executive_responsible/all_companies/_filter.html.slim
= render partial: 'admin/company_universes/util'

= panel_section(name: t("views.admin.bookings.filter"), class: 'filter widget-box') do
  = form_tag all_companies_executive_responsible_company_universes_path, method: :get, class: 'form-horizontal' do
    .row
      .col-sm-6
        = label_tag :q, "#{t('views.executive_responsible.all_companies.filter.name')}", class: 'control-label no-left-padding'
        input.form-control name='by_name' value="#{params[:by_name] || ''}"

      .col-sm-6
        = label_tag :q, "#{t('views.executive_responsible.all_companies.filter.social_name')}", class: 'control-label no-left-padding'
        input.form-control name='by_social_name' value="#{params[:by_social_name] || ''}"

    .row
      .col-sm-4
        = label_tag :q, "#{t('views.executive_responsible.all_companies.filter.cnpj')}", class: 'control-label no-left-padding'
        input.form-control name='by_cnpj' value="#{params[:by_cnpj] || ''}"

      .col-sm-4
        = label_tag :q, "#{t('views.executive_responsible.all_companies.filter.city')}", class: 'control-label no-left-padding'
        input.form-control name='by_city' id='citiesHash' value="#{params[:by_city] || ''}"

      .col-sm-4
        = label_tag :q, "#{t('views.executive_responsible.all_companies.filter.region')}", class: 'control-label no-left-padding'
        input.form-control name='by_region' id='companyRegionsHash' value="#{params[:by_region] || ''}"

    br
    .row
      .col-lg-3.col-md-4.col-sm-6.col-xs-12
        = label_tag :q, "#{t('views.executive_responsible.all_companies.filter.phone_number')}", class: 'control-label no-left-padding'
        .input-group
          span.input-group-addon.size-35-percent
            | #{t("views.admin.bookings.enter")}
          input.js-date-picker.form-control.text-right.js-mask-date.js-initial-date name='by_talked_phone_date[initial_date]' value="#{params[:by_talked_phone_date].try(:[],:initial_date) || ''}"
          span.input-group-addon
            i.icon-calendar.bigger-110
        .input-group
          span.input-group-addon.size-35-percent
            | #{t("views.admin.bookings.and")}
          input.js-date-picker.form-control.text-right.js-mask-date.js-final-date name='by_talked_phone_date[final_date]' value="#{params[:by_talked_phone_date].try(:[],:final_date) || ''}"
          span.input-group-addon
            i.icon-calendar.bigger-110
        .clearfix
      .col-lg-3.col-md-4.col-sm-6.col-xs-12
        = label_tag :q, "#{t('views.executive_responsible.all_companies.filter.meeting_held')}", class: 'control-label no-left-padding'
        .input-group
          span.input-group-addon.size-35-percent
            | #{t("views.admin.bookings.enter")}
          input.js-date-picker.form-control.text-right.js-mask-date.js-initial-date name='by_already_face_to_face_meeting_date[initial_date]' value="#{params[:by_already_face_to_face_meeting_date].try(:[],:initial_date) || ''}"
          span.input-group-addon
            i.icon-calendar.bigger-110
        .input-group
          span.input-group-addon.size-35-percent
            | #{t("views.admin.bookings.and")}
          input.js-date-picker.form-control.text-right.js-mask-date.js-final-date name='by_already_face_to_face_meeting_date[final_date]' value="#{params[:by_already_face_to_face_meeting_date].try(:[],:final_date) || ''}"
          span.input-group-addon
            i.icon-calendar.bigger-110
        .clearfix
      .col-lg-3.col-md-4.col-sm-6.col-xs-12
        = label_tag :q, "#{t('views.executive_responsible.all_companies.filter.creation_company')}", class: 'control-label no-left-padding'
        .input-group
          span.input-group-addon.size-35-percent
            | #{t("views.admin.bookings.enter")}
          input.js-date-picker.form-control.text-right.js-mask-date.js-initial-date name='by_company_registered_date[initial_date]' value="#{params[:by_company_registered_date].try(:[],:initial_date) || ''}"
          span.input-group-addon
            i.icon-calendar.bigger-110
        .input-group
          span.input-group-addon.size-35-percent
            | #{t("views.admin.bookings.and")}
          input.js-date-picker.form-control.text-right.js-mask-date.js-final-date name='by_company_registered_date[final_date]' value="#{params[:by_company_registered_date].try(:[],:final_date) || ''}"
          span.input-group-addon
            i.icon-calendar.bigger-110
        .clearfix
      .col-lg-3.col-md-4.col-sm-6.col-xs-12
        = label_tag :q, "#{t('views.executive_responsible.all_companies.filter.follow_up_date')}", class: 'control-label no-left-padding'
        .input-group
          span.input-group-addon.size-35-percent
            | #{t("views.admin.bookings.enter")}
          input.js-date-picker.form-control.text-right.js-mask-date.js-initial-date name='by_follow_up_date[initial_date]' value="#{params[:by_follow_up_date].try(:[],:initial_date) || ''}"
          span.input-group-addon
            i.icon-calendar.bigger-110
        .input-group
          span.input-group-addon.size-35-percent
            | #{t("views.admin.bookings.and")}
          input.js-date-picker.form-control.text-right.js-mask-date.js-final-date name='by_follow_up_date[final_date]' value="#{params[:by_follow_up_date].try(:[],:final_date) || ''}"
          span.input-group-addon
            i.icon-calendar.bigger-110
        .clearfix
    hr


    = submit_tag t("views.admin.bookings.filter"), class: 'btn btn-sm btn-success pull-right size-20-percent cpy-filter-button margin-left-10px'
    = link_to t("views.admin.bookings.remove_filter"), all_companies_executive_responsible_company_universes_path, class: 'btn btn-sm btn-danger pull-right size-20-percent remove-button cpy-remove-filter-button'

    .clearfix